package factorio

import (
	"fmt"
	"sort"
	"strings"
)

// `fklua docs`: per-language API reference from the API's own descriptions.
//
// Generated in the same pass as the bindings and from the same Report, which is
// the whole point: documentation that is produced by a different walk of the
// same JSON can disagree with the bindings, and eventually will. Here a member
// appears in the docs if and only if it was emitted, and under the name it was
// emitted as.
//
// So the docs also answer a question the bindings alone cannot: WHAT IS NOT
// HERE. A mod author hunting for a member that does not exist needs to know
// whether it was never in the API or was skipped, and the skip reasons are
// already collected.

// DocOptions selects what to render.
type DocOptions struct {
	// Lang is "go" or "rust"; it decides the member names shown.
	Lang string
	// Names maps "Class::member/kind" to the emitted identifier, from the
	// generator that produced the bindings being documented.
	Names map[string]string
}

// Docs renders a markdown reference for one language.
func Docs(a *API, r Report, evs EventReport, opt DocOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Factorio %s API reference (%s)\n\n", a.ApplicationVersion, opt.Lang)
	b.WriteString("Generated by `fklua docs` from `runtime-api.json`, in the same pass\n")
	b.WriteString("as the bindings. A member appears here exactly when it was emitted,\n")
	b.WriteString("and under the name it was emitted as.\n\n")

	byClass := map[string][]Member{}
	for _, m := range r.Members {
		if m.Class != "" {
			byClass[m.Class] = append(byClass[m.Class], m)
		}
	}

	// Contents first: 156 classes is too many to scroll.
	var classes []string
	for _, c := range a.Classes {
		if len(byClass[c.Name]) > 0 {
			classes = append(classes, c.Name)
		}
	}
	sort.Strings(classes)
	fmt.Fprintf(&b, "%d classes, %d members bound of %d.\n\n",
		len(classes), len(opt.Names), len(r.Members))
	b.WriteString("## Contents\n\n")
	for _, c := range classes {
		fmt.Fprintf(&b, "- [%s](#%s)\n", c, strings.ToLower(c))
	}

	descByClass := map[string]Class{}
	for _, c := range a.Classes {
		descByClass[c.Name] = c
	}

	for _, cls := range classes {
		c := descByClass[cls]
		fmt.Fprintf(&b, "\n## %s\n\n", cls)
		if c.Parent != "" {
			// Inheritance is real and invisible in the member lists, so saying
			// so is not decoration: a member reached through a parent appears
			// in neither list.
			fmt.Fprintf(&b, "*Inherits from [%s](#%s).*\n\n", c.Parent, strings.ToLower(c.Parent))
		}
		if d := oneLine(c.Description); d != "" {
			fmt.Fprintf(&b, "%s\n\n", d)
		}

		members := byClass[cls]
		sort.Slice(members, func(i, j int) bool {
			if members[i].Name != members[j].Name {
				return members[i].Name < members[j].Name
			}
			return members[i].Kind < members[j].Kind
		})
		for _, m := range members {
			key := fmt.Sprintf("%s::%s/%d", m.Class, m.Name, m.Kind)
			name, bound := opt.Names[key]
			if !bound {
				continue
			}
			fmt.Fprintf(&b, "### `%s`\n\n", name)
			fmt.Fprintf(&b, "`%s::%s` — %s\n\n", m.Class, m.Name, kindWord(m.Kind))
			if d := oneLine(memberDescription(descByClass[cls], m)); d != "" {
				fmt.Fprintf(&b, "%s\n\n", d)
			}
		}
	}

	if len(evs.Events) > 0 {
		b.WriteString("\n## Events\n\n")
		evNames := append([]EventDef(nil), evs.Events...)
		sort.Slice(evNames, func(i, j int) bool { return evNames[i].Name < evNames[j].Name })
		for _, e := range evNames {
			fmt.Fprintf(&b, "- `%s` (id %d)\n", e.Name, e.ID)
		}
	}

	// What is NOT here, and why. A reader hunting for a missing member needs to
	// know whether it was never in the API or was skipped.
	if len(r.Reasons) > 0 {
		b.WriteString("\n## Not bound\n\n")
		b.WriteString("These members exist in the API and FkLua does not carry them.\n")
		b.WriteString("A skipped member is absent rather than present-and-broken, which\n")
		b.WriteString("is deliberate: a binding that exists and does the wrong thing is\n")
		b.WriteString("worse than one you cannot call.\n\n")
		var reasons []string
		for k := range r.Reasons {
			reasons = append(reasons, k)
		}
		sort.Strings(reasons)
		for _, k := range reasons {
			fmt.Fprintf(&b, "- %s — **%d**\n", k, r.Reasons[k])
		}
	}
	return b.String()
}

func kindWord(k int) string {
	switch k {
	case MemberGet:
		return "attribute (read)"
	case MemberSet:
		return "attribute (write)"
	case MemberGetEq:
		return "attribute (host-side compare)"
	case MemberGetHandle:
		return "attribute (as a handle)"
	}
	return "method"
}

// memberDescription finds the API's own prose for a member.
func memberDescription(c Class, m Member) string {
	if m.Kind == MemberCall {
		for _, x := range c.Methods {
			if x.Name == m.Name {
				return x.Description
			}
		}
		return ""
	}
	for _, x := range c.Attributes {
		if x.Name == m.Name {
			return x.Description
		}
	}
	return ""
}

// oneLine flattens the API's prose onto a single line.
//
// The descriptions carry newlines and Factorio's own `[link](runtime:Foo)`
// markup, which is not markdown any renderer here understands. Stripping the
// scheme leaves a readable label rather than a dead link.
func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	for {
		i := strings.Index(s, "](runtime:")
		if i < 0 {
			break
		}
		j := strings.Index(s[i:], ")")
		if j < 0 {
			break
		}
		s = s[:i] + "]" + s[i+j+1:]
	}
	s = strings.ReplaceAll(s, "](", " (")
	return strings.Join(strings.Fields(s), " ")
}
