package factorio

import (
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Techrocket9/fklua/internal/ir"
	"github.com/Techrocket9/fklua/internal/luagen"
	"github.com/Techrocket9/fklua/internal/luahost"
	"github.com/Techrocket9/fklua/internal/wasm"
)

// THE PERSISTENT HANDLE SPACE, ACROSS A SAVE.
//
// fk_abi.lua's own header says a retained handle "lives in `storage` so it
// survives a save. A guest that stashes an entity across a save gets the entity
// back rather than a dangling index." Both halves of the mechanism were there --
// M.persistent_table() hands over the live table, M.adopt() takes it back and
// rebuilds the free list -- and until this landed the shipped fk_mod.lua called
// NEITHER, so the whole space was session-scoped and the documentation was a
// promise with nothing behind it.
//
// The symptom arrives a long way from the cause, which is why the first mod to
// use the feature (fklua-ports-samples, finding G3) spent a while
// looking elsewhere: the guest's own state comes back intact, because that half
// really is persisted, and then every handle inside it resolves to
// ERR_BAD_HANDLE. A guest that reasonably reads a dead handle as "that entity
// was destroyed" quietly forgets everything it was tracking, on every load.
//
// The tests below drive the real control.lua protocol -- fresh Lua state, fresh
// require, only `storage` crossing -- because that is where the defect lived:
// nothing was wrong inside fk_abi.lua, and no test of fk_abi.lua could see it.

// A guest that stashes a handle across a save.
//
//	fk_on_init   game.stash -> a handle; retain it; remember the number
//	fk_on_tick   call `mark` on the REMEMBERED number, then report the handle,
//	             the status and the value back to the host as three SETs
//
// IT REPORTS THROUGH HOST CALLS RATHER THAN THROUGH MEMORY, and that is what
// makes one guest cover both persist modes: control.lua keeps its instance in a
// local, so the only way to read a guest word from outside is `storage.fk_mem`
// -- which exists in table mode and is a set of packed pages in the other.
// Three SETs on the stand-in `game` are mode-independent by construction.
const retainWAT = `(module
	(import "fk" "call" (func $call (param i32 i32 i32 i32) (result i32)))
	(import "fk" "retain" (func $retain (param i32) (result i32)))
	(memory 1)
	(func (export "fk_on_init")
		(drop (call $call (i32.const 2) (i32.const 1) (i32.const 64) (i32.const 80)))
		(i32.store (i32.const 0) (call $retain (i32.load (i32.const 80)))))
	(func (export "fk_on_tick") (param $tick i32)
		(i32.store (i32.const 8)
			(call $call (i32.load (i32.const 0)) (i32.const 2)
				(i32.const 64) (i32.const 84)))
		(i32.store (i32.const 88) (i32.load (i32.const 0)))
		(drop (call $call (i32.const 2) (i32.const 5) (i32.const 88) (i32.const 96)))
		(i32.store (i32.const 88) (i32.load (i32.const 8)))
		(drop (call $call (i32.const 2) (i32.const 4) (i32.const 88) (i32.const 96)))
		(i32.store (i32.const 88) (i32.load (i32.const 84)))
		(drop (call $call (i32.const 2) (i32.const 3) (i32.const 88) (i32.const 96)))))`

var retainExports = []string{"fk_on_init", "fk_on_tick"}

// The member table the guest above was compiled against. What is under test is
// the HANDLE and not the marshalling, so every member is a plain scalar: member
// 1 hands back an OBJECT (K_HANDLE, so the host wraps it in a transient handle),
// member 2 reads a u32 off whatever object a handle names, and 3..5 are SETs
// the guest uses to report.
const retainMembers = `-- Generated by fklua (test fixture).
local U32 = { args = { { name = "v", kind = 6, at = 0 } }, rets = {} }
return { api_version = 0, application_version = "2.0.77", members = {
  [1] = { kind = 1, name = "stash", class = "LuaGameScript", argsize = 0,
          retsize = 4, sig = { args = {}, rets = { { name = "value", kind = 11, at = 0 } } } },
  [2] = { kind = 1, name = "mark", class = "LuaObject", valid = true, argsize = 0,
          retsize = 4, sig = { args = {}, rets = { { name = "value", kind = 6, at = 0 } } } },
  [3] = { kind = 2, name = "value_out",  class = "LuaGameScript", argsize = 4, retsize = 0, sig = U32 },
  [4] = { kind = 2, name = "status_out", class = "LuaGameScript", argsize = 4, retsize = 0, sig = U32 },
  [5] = { kind = 2, name = "handle_out", class = "LuaGameScript", argsize = 4, retsize = 0, sig = U32 },
} }
`

// packRetain packages the guest above at one persist mode and build identity.
func packRetain(t *testing.T, mode luagen.PersistMode, id string) string {
	t.Helper()
	m, err := wasm.DecodeWAT(retainWAT)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	im, err := ir.BuildModule(m)
	if err != nil {
		t.Fatalf("ir: %v", err)
	}
	chunk, err := luagen.EmitModuleWith(im, luagen.Options{Persist: mode, BuildID: id})
	if err != nil {
		t.Fatalf("emit: %v", err)
	}
	pkg := &Package{
		Info: Info{
			Name: "fk-retain", Version: "0.1.0", Title: "Retain",
			Author: "FkLua", FactorioVersion: DefaultFactorioVersion,
		},
		Chunk:    chunk,
		Exports:  retainExports,
		APITable: retainMembers,
	}
	dir, err := pkg.WriteDir(t.TempDir())
	if err != nil {
		t.Fatalf("WriteDir: %v", err)
	}
	return dir
}

// retainStub is saveLoadStub with a stand-in `game` in it.
//
// The stub object is a plain table, which is what a LuaObject looks like from
// this side: a `valid` field the handle table checks and one attribute to read
// back. `deepcopy` of `storage` between the sessions is what makes the test
// honest -- it models Factorio serializing the reference rather than letting a
// live Lua table sneak across a boundary the real game rebuilds.
func retainStub(modDir string, firstTicks, secondTicks int) string {
	return fmt.Sprintf(expandClearLoaded(`package.path = %q
defines = { events = { on_tick = 1 } }

local function deepcopy(v)
  if type(v) ~= "table" then return v end
  local out = {}
  for k, x in pairs(v) do out[deepcopy(k)] = deepcopy(x) end
  return out
end

logged = {}
function log(s) logged[#logged + 1] = s end

function session(saved, ticks, dir)
  local handlers = {}
  script = {
    mod_name = "fk-retain",
    on_init = function(f) handlers.on_init = f end,
    on_load = function(f) handlers.on_load = f end,
    on_configuration_changed = function(f) handlers.on_config = f end,
    on_event = function(ev, f) handlers[ev] = f end,
  }
  storage = saved and deepcopy(saved) or {}
  -- A FRESH stand-in game every session, holding a FRESH stand-in entity: the
  -- one the previous session retained can only reach this one through storage.
  game = { stash = { valid = true, mark = 4242 } }
  if dir then package.path = dir end
  --@CLEAR_LOADED@
  local ok, err = pcall(require, "control")
  if not ok then error(err, 0) end

  if saved then
    if handlers.on_load then handlers.on_load() end
    if handlers.on_config then handlers.on_config() end
  else
    if handlers.on_init then handlers.on_init() end
  end
  for tick = 1, ticks do
    local f = handlers[defines.events.on_tick]
    if f then f({ tick = tick }) end
  end
  return storage, game
end

local first, gameA = session(nil, %d)
local second, gameB = session(first, %d)
`), filepath.Join(modDir, "?.lua"), firstTicks, secondTicks)
}

// report prints what the second session's guest said, plus what `storage` holds,
// so a failure names which half of the mechanism was missing.
const retainReport = `
print("handle " .. tostring(gameB.handle_out))
print("status " .. tostring(gameB.status_out))
print("value " .. tostring(gameB.value_out))
local n = -1
if second.fk_handles then
  n = 0
  for _ in pairs(second.fk_handles) do n = n + 1 end
end
print("saved handles " .. n)
`

// F1, at the smallest scale that can express it: a handle retained before a
// save still names its object after the load.
//
// `value 4242` is the whole assertion -- the guest called a member on a number
// it remembered across a fresh Lua state and reached the object again. Before
// the fix this was `status 1` (ERR_BAD_HANDLE), `value 0` and
// `saved handles -1`: nothing had ever been written to storage for the handle
// table to come back from.
func TestARetainedHandleSurvivesASave(t *testing.T) {
	for _, mode := range []struct {
		name string
		m    luagen.PersistMode
	}{
		{"table", luagen.PersistTable},
		{"packed", luagen.PersistPacked},
	} {
		t.Run(mode.name, func(t *testing.T) {
			h, err := luahost.Find()
			if err != nil {
				t.Skipf("skipping: %v", err)
			}
			dir := packRetain(t, mode.m, "build-one")
			out, err := h.RunString(retainStub(dir, 0, 1) + retainReport)
			if err != nil {
				t.Fatalf("run: %v", err)
			}
			want := strings.Join([]string{
				"handle 10",       // the first persistent slot
				"status 0",        // OK, not ERR_BAD_HANDLE
				"value 4242",      // and it really reached the object
				"saved handles 1", // which it did through storage
			}, "\n")
			if got := strings.TrimSpace(out); got != want {
				t.Errorf("got:\n%s\nwant:\n%s\n(a retained handle must survive a "+
					"save: fk_abi.lua's header promises it, and nothing in "+
					"fk_mod.lua published or adopted the persistent table)", got, want)
			}
		})
	}
}

// The coherence half, and it is the half a partial fix gets wrong.
//
// A rebuilt guest is handed a FRESH heap (see state_load and the fk_migrate
// split), so every handle NUMBER it was holding died with the heap that held
// it. Adopting the saved handle table anyway would leave the previous build's
// objects pinned in `storage` forever, reachable by nobody -- a leak that grows
// with every rebuild and that no guest can free, because freeing needs the
// number.
//
// So the handle table follows the heap exactly: adopted when the heap is,
// discarded when the heap is, republished empty by the same state_init that
// republishes the heap.
func TestARebuiltGuestDoesNotInheritRetainedHandles(t *testing.T) {
	h, err := luahost.Find()
	if err != nil {
		t.Skipf("skipping: %v", err)
	}
	a := packRetain(t, luagen.PersistTable, "build-A")
	b := packRetain(t, luagen.PersistTable, "build-B")
	out, err := h.RunString(fmt.Sprintf(`%s
local third, gameC = session(first, 1, %q)
local n = 0
for _ in pairs(third.fk_handles or {}) do n = n + 1 end
print("carried handles " .. n)
print("published " .. tostring(third.fk_handles ~= nil))
print("status " .. tostring(gameC.status_out))
`, retainStub(a, 0, 0), filepath.Join(b, "?.lua")))
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	want := strings.Join([]string{
		"carried handles 0", // build A's stash is not pinned in build B's save
		"published true",    // but the table is there for build B to retain into
		"status 1",          // and build B's own read finds a dead handle, as it must
	}, "\n")
	if got := strings.TrimSpace(out); got != want {
		t.Errorf("got:\n%s\nwant:\n%s\n(a discarded heap must discard its handles "+
			"with it -- adopting them would pin the previous build's objects in "+
			"storage with no number left that could free them)", got, want)
	}
}

// --persist=none keeps writing nothing, handles included.
//
// It is not an oversight that the space is tied to the persist mode. A handle
// number means nothing without the guest memory that remembers it, and under
// `none` that memory is rebuilt from the data segments on every load -- so a
// handle table carried across would be entries no guest could ever name again.
func TestNoneModeStoresNoHandlesEither(t *testing.T) {
	h, err := luahost.Find()
	if err != nil {
		t.Skipf("skipping: %v", err)
	}
	dir := packRetain(t, luagen.PersistNone, "build-one")
	out, err := h.RunString(retainStub(dir, 0, 0) + `
local n = 0
for _ in pairs(second) do n = n + 1 end
print("storage keys " .. n)
`)
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if got, want := strings.TrimSpace(out), "storage keys 0"; got != want {
		t.Errorf("got %q, want %q", got, want)
	}
}

// The handle table is published from state_init, which runs in on_init and in
// on_configuration_changed -- never in on_load, which Factorio runs on every
// client joining a multiplayer game and where a write is a desync waiting to
// happen. Adopting is a READ of storage and a write to fk_abi's own upvalues,
// which is a different thing; this pins that the distinction survived the fix.
//
// THE FREEZE IS A PROXY OVER AN EMPTY TABLE, for persist_test.go's
// TestOnLoadDoesNotWriteToStorage's reason and with the same history: this
// carried the populated-copy form too, so it caught only a write to a key no
// session had ever created -- and fk_handles, the key this test is actually
// about, is present in every save it looks at.
func TestAdoptingHandlesDoesNotWriteStorageOnLoad(t *testing.T) {
	h, err := luahost.Find()
	if err != nil {
		t.Skipf("skipping: %v", err)
	}
	dir := packRetain(t, luagen.PersistTable, "build-one")
	script := retainStub(dir, 0, 0) + expandClearLoaded(`
local function deepcopy(v)
  if type(v) ~= "table" then return v end
  local o = {}
  for k, x in pairs(v) do o[deepcopy(k)] = deepcopy(x) end
  return o
end
local real = {}
for k, v in pairs(first) do real[k] = deepcopy(v) end
local frozen = setmetatable({}, {
  __index = real,
  __newindex = function(_, k)
    error("on_load wrote storage." .. tostring(k), 0)
  end,
})

local handlers = {}
script = {
  mod_name = "fk-retain",
  on_init = function(f) handlers.on_init = f end,
  on_load = function(f) handlers.on_load = f end,
  on_configuration_changed = function(f) handlers.on_config = f end,
  on_event = function(ev, f) handlers[ev] = f end,
}
storage = frozen
game = { stash = { valid = true, mark = 4242 } }
--@CLEAR_LOADED@
require("control")
handlers.on_load()
print("clean")
`)
	out, err := h.RunString(script)
	if err != nil {
		t.Fatalf("on_load wrote to storage: %v", err)
	}
	if got := strings.TrimSpace(out); got != "clean" {
		t.Errorf("got %q", got)
	}

	// The positive control, over fk_handles specifically: the key this test is
	// about, and one the save already has.
	t.Run("the freeze catches a write to the handle table", func(t *testing.T) {
		out, err := h.RunString(script + `
storage.fk_handles = "clobbered"
print("NOT CAUGHT")
`)
		if err == nil {
			t.Fatalf("the frozen storage did not raise on a write to fk_handles, "+
				"a key the save ALREADY HAS -- so the assertion above is vacuous "+
				"for exactly the key it exists to protect.\n%s", out)
		}
		if !strings.Contains(err.Error(), "on_load wrote storage.fk_handles") {
			t.Errorf("raised, but not from the freeze: %v", err)
		}
	})
}
