package factorio

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// SCENARIOS a mod ships, and the one line of Lua each of them is.
//
// A scenario's control.lua is a FULL CONTROL STAGE -- its own Lua state, its own
// events, its own `storage` -- so it is not a thing this compiler can generate a
// guest into. What the base game does instead is the whole of this feature: a
// scenario a mod ships is a one-line require into the mod's own tree, and the
// mod's control stage does the work. `fklua mod` already writes exactly that
// file for the mod root, so what was missing was somewhere to put a second copy
// of it.
//
// It is a PACKAGING gap and it is small: a scenario directory needs `control.lua`
// and nothing else that fklua could produce, and an author's own scenario assets
// (`description.json`, `blueprint.zip`, a locale directory) come in through the
// include tree like every other authored file.
//
// THE SHAPE IS `[stages]`', DELIBERATELY. A chain of requires with one token
// standing for the generated thing is a form this project already has, an author
// who has met one has met the other, and the mid-migration case -- a scenario
// that requires the mod AND some Lua of its own, in an order the author states --
// is expressible without inventing a second mechanism.

// ScenarioControlEntry is the token a scenario chain uses to name the mod's own
// generated control stage.
//
// It is a token rather than a path for GuestStageEntry's reason and one of its
// own: the require it becomes is `__<modname>__/control`, which cannot be written
// down in the manifest without repeating the mod's name there -- and a name
// written twice is this repo's most-repeated failure shape.
const ScenarioControlEntry = "@control"

// ScenarioDir is where Factorio looks for a mod's scenarios.
const ScenarioDir = "scenarios"

// scenarioNameRE is what may name a scenario directory.
//
// Deliberately narrower than what a filesystem allows: this string becomes a
// path inside a zip and a directory on disk, so a separator or a `..` in it is a
// package that writes outside itself. Factorio's own scenario names are of this
// shape and the refusal names the rule rather than the character.
var scenarioNameRE = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9 _-]*$`)

// scenarioFiles renders the scenario control stages this package ships.
//
// THE RULES, and each is `stageChains`' with one word changed:
//
//   - a chain naming @control where the mod HAS no control guest is an error at
//     package time. It is the one arrangement that is certainly a mistake, and
//     the alternative is a scenario that loads and does nothing;
//   - a chain with no @control is a pure-Lua scenario, which is both the far end
//     of a migration and what a scenario that only sets up a map wants;
//   - an absent [scenarios] section generates nothing at all, so a project
//     written before this key existed emits byte for byte what it emitted before.
func (p *Package) scenarioFiles() (map[string]string, error) {
	if len(p.Scenarios) == 0 {
		return nil, nil
	}
	out := map[string]string{}
	for _, name := range sortedScenarioNames(p.Scenarios) {
		if !scenarioNameRE.MatchString(name) {
			return nil, fmt.Errorf("[scenarios] %q: a scenario name becomes a "+
				"directory inside the mod, so it may hold only letters, digits, "+
				"spaces, dashes and underscores and must start with a letter or a "+
				"digit", name)
		}
		chain := p.Scenarios[name]
		for _, entry := range chain {
			if entry != ScenarioControlEntry {
				continue
			}
			if p.Chunk == "" {
				return nil, fmt.Errorf("[scenarios] %s names %s and this mod has "+
					"no control guest; either pass one or take %s out of the chain",
					name, ScenarioControlEntry, ScenarioControlEntry)
			}
		}
		out[ScenarioDir+"/"+name+"/control.lua"] = scenarioFile(p.Info.Name, name, chain)
	}
	return out, nil
}

// scenarioFile renders one scenario's control.lua.
func scenarioFile(mod, scenario string, chain []string) string {
	var b strings.Builder
	b.WriteString("-- Generated by fklua. Do not edit.\n")
	b.WriteString("--\n")
	fmt.Fprintf(&b, "-- The %q scenario's control stage. The order below is\n", scenario)
	b.WriteString("-- [scenarios] in fklua.toml; see docs/generated-files.md in the\n")
	b.WriteString("-- FkLua repo.\n")
	for _, entry := range chain {
		if entry == ScenarioControlEntry {
			// THE MOD'S OWN control.lua, BY THE CROSS-MOD PATH. A scenario runs in
			// its own Lua state and its own directory, so a bare require would look
			// beside the scenario rather than at the mod root -- and `__name__/path`
			// is the form Factorio resolves against a mod's tree from anywhere,
			// which is what the base game's own scenario shims use.
			fmt.Fprintf(&b, "require(\"__%s__/control\")\n", mod)
			continue
		}
		fmt.Fprintf(&b, "require(%q)\n", entry)
	}
	return b.String()
}

func sortedScenarioNames(m map[string][]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	// Sorted rather than walked, for the reason every other map in this package
	// is: Go randomises a map walk and a packager that emitted its files in a
	// different order on every run would make every rebuild a diff.
	sort.Strings(out)
	return out
}
