package factorio

import (
	"strings"
	"testing"

	"github.com/Techrocket9/fklua/internal/luahost"
)

func scenarioPkg(t *testing.T, chunk string, scen map[string][]string) *Package {
	t.Helper()
	return &Package{
		Info: Info{Name: "fk-scen", Version: "0.1.0", Title: "t", Author: "x",
			FactorioVersion: DefaultFactorioVersion},
		Chunk: chunk, APITable: emptyAPITable, Scenarios: scen,
	}
}

// A MOD-SHIPPED SCENARIO IS ONE LINE OF LUA, and until this key existed there
// was nowhere to put it.
//
// A scenario's control.lua is a full control stage in its own Lua state, so it
// is not something this compiler generates a guest into; the base game's own
// convention is a one-line require into the mod's tree, which is exactly the
// file `fklua mod` already writes for the mod root. What was missing was a way
// to say "and a copy of it here".
func TestAScenarioKeyWritesTheShim(t *testing.T) {
	p := scenarioPkg(t, "-- chunk\n", map[string][]string{
		"freeplay-plus": {ScenarioControlEntry},
	})
	files, err := p.Files()
	if err != nil {
		t.Fatal(err)
	}
	got, ok := files["scenarios/freeplay-plus/control.lua"]
	if !ok {
		t.Fatalf("no scenario shim was written; got %v", sortedFileNames(files))
	}
	// THE CROSS-MOD PATH, not a bare require: a scenario runs in its own
	// directory, so `require("control")` would look beside the scenario rather
	// than at the mod root.
	if !strings.Contains(got, `require("__fk-scen__/control")`) {
		t.Errorf("the shim does not require the mod's own control stage by the "+
			"cross-mod path:\n%s", got)
	}
	if !strings.Contains(got, "Generated by fklua") {
		t.Errorf("the shim does not say it is generated:\n%s", got)
	}
}

// A chain rather than a flag, which is [stages]' own shape: a scenario that
// wants the mod AND some Lua of its own says so in an order it states.
func TestAScenarioChainKeepsItsOrder(t *testing.T) {
	p := scenarioPkg(t, "-- chunk\n", map[string][]string{
		"custom": {"__fk-scen__/scenario-setup", ScenarioControlEntry},
	})
	files, err := p.Files()
	if err != nil {
		t.Fatal(err)
	}
	got := files["scenarios/custom/control.lua"]
	setup := strings.Index(got, `require("__fk-scen__/scenario-setup")`)
	ctrl := strings.Index(got, `require("__fk-scen__/control")`)
	if setup < 0 || ctrl < 0 {
		t.Fatalf("both requires should be present:\n%s", got)
	}
	if setup > ctrl {
		t.Errorf("the chain was reordered; the author's order is the whole "+
			"point of a chain:\n%s", got)
	}
}

// A chain naming @control with no control guest is the one arrangement that is
// certainly a mistake, and the alternative is a scenario that loads and does
// nothing. Same rule as [stages] naming @guest for an unexported hook.
func TestAScenarioNamingTheControlStageWithoutOneIsRefused(t *testing.T) {
	p := scenarioPkg(t, "", map[string][]string{"solo": {ScenarioControlEntry}})
	p.DataChunk = "-- data\n"
	p.DataExports = []string{"fk_data"}
	if _, err := p.Files(); err == nil {
		t.Fatal("a scenario naming @control on a mod with no control guest was " +
			"accepted; that is a scenario that loads and does nothing")
	} else if !strings.Contains(err.Error(), ScenarioControlEntry) {
		t.Errorf("the refusal does not name %s: %v", ScenarioControlEntry, err)
	}
}

// A PURE-LUA SCENARIO IS LEGAL, which is both the far end of a migration and
// what a scenario that only sets a map up wants.
func TestAScenarioWithNoControlEntryIsPureLua(t *testing.T) {
	p := scenarioPkg(t, "", map[string][]string{"maponly": {"__fk-scen__/mapsetup"}})
	p.DataChunk = "-- data\n"
	p.DataExports = []string{"fk_data"}
	files, err := p.Files()
	if err != nil {
		t.Fatal(err)
	}
	got := files["scenarios/maponly/control.lua"]
	if strings.Contains(got, "/control\"") {
		t.Errorf("a chain with no %s should not require the control stage:\n%s",
			ScenarioControlEntry, got)
	}
	if !strings.Contains(got, `require("__fk-scen__/mapsetup")`) {
		t.Errorf("the chain's own require is missing:\n%s", got)
	}
}

// A NAME BECOMES A DIRECTORY INSIDE THE PACKAGE, so a separator in it is a
// package that writes outside itself -- into a zip entry or onto the disk. The
// refusal names the rule rather than the character.
func TestAScenarioNameThatIsAPathIsRefused(t *testing.T) {
	for _, bad := range []string{"../escape", "a/b", "", " leading"} {
		p := scenarioPkg(t, "-- chunk\n", map[string][]string{bad: {ScenarioControlEntry}})
		if _, err := p.Files(); err == nil {
			t.Errorf("the scenario name %q was accepted", bad)
		}
	}
}

// AND AN INCLUDED control.lua UNDER scenarios/ IS THE HALFWAY HOUSE, with the
// same remedy [stages] gives its own: the hand-written file goes back into the
// chain rather than being renamed away.
func TestAnIncludedScenarioControlCollidesWithARemedy(t *testing.T) {
	p := scenarioPkg(t, "-- chunk\n", map[string][]string{"old": {ScenarioControlEntry}})
	p.Extra = map[string]string{"scenarios/old/control.lua": "-- theirs\n"}
	p.extraFrom = map[string]string{"scenarios/old/control.lua": "mod-data"}
	_, err := p.Files()
	if err == nil {
		t.Fatal("an included scenario control.lua silently lost to the generated one")
	}
	if !strings.Contains(err.Error(), "[scenarios]") {
		t.Errorf("the refusal does not name the key that is the way through it: %v",
			err)
	}
}

// THE BACK-COMPATIBILITY HALF, and it is the reason the key is free.
//
// A project written before [scenarios] existed has no section for it, and
// TestAProjectWithNoDataModuleIsByteIdentical is the standing gate for exactly
// this shape one key over. Absent means absent: not an empty scenarios/
// directory, not an empty file, nothing.
func TestAPackageWithNoScenariosIsByteIdentical(t *testing.T) {
	with := scenarioPkg(t, "-- chunk\n", nil)
	without := scenarioPkg(t, "-- chunk\n", map[string][]string{})
	a, err := with.Files()
	if err != nil {
		t.Fatal(err)
	}
	b, err := without.Files()
	if err != nil {
		t.Fatal(err)
	}
	if len(a) != len(b) {
		t.Fatalf("a nil map and an empty one produced %d and %d files", len(a), len(b))
	}
	for name, body := range a {
		if b[name] != body {
			t.Errorf("%s differs", name)
		}
		if strings.HasPrefix(name, ScenarioDir+"/") {
			t.Errorf("a package with no scenarios wrote %s", name)
		}
	}
}

// AND THE SHIM PARSES, under the real Lua the game uses.
//
// It is four lines of comment and a require, which is exactly the kind of file
// nobody checks -- and a scenario whose control.lua does not parse is a game
// that will not start, discovered by whoever picked the scenario rather than by
// whoever packaged it.
func TestTheScenarioShimParses(t *testing.T) {
	h, err := luahost.Find()
	if err != nil {
		t.Skipf("skipping: %v", err)
	}
	p := scenarioPkg(t, "-- chunk\n", map[string][]string{
		"freeplay-plus": {ScenarioControlEntry, "__fk-scen__/extra"},
	})
	files, err := p.Files()
	if err != nil {
		t.Fatal(err)
	}
	body := files["scenarios/freeplay-plus/control.lua"]
	// load rather than a RUN, and rather than loadfile: the requires name a mod
	// that is not there, so what is under test is the FILE and not what it pulls
	// in -- and Factorio's sandbox has no loadfile, which is the kind of thing a
	// test written against stock Lua gets wrong.
	out, err := h.RunString(`
local f, err = load(` + luaQuote(body) + `, "scenario")
print("parsed " .. tostring(f ~= nil) .. " " .. tostring(err))
`)
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	if got := strings.TrimSpace(out); got != "parsed true nil" {
		t.Errorf("the generated scenario shim does not parse: %s", got)
	}
}

func sortedFileNames(files map[string]string) []string {
	var out []string
	for k := range files {
		out = append(out, k)
	}
	return out
}

// THE MANIFEST ROUND-TRIPS, which is what `fklua init` rewriting a project must
// not lose.
//
// [scenarios] is the one section whose KEYS are the author's own rather than a
// fixed set, so the parser cannot check a key against a list the way [stages]
// does -- which makes a round trip the only thing that says a name survives at
// all.
func TestTheScenarioSectionRoundTrips(t *testing.T) {
	src := `[mod]
name = "demo"
version = "0.1.0"

[fklua]
api = "` + DefaultAPIVersion + `"

[scenarios]
freeplay-plus = ["@control"]
maponly = ["__demo__/mapsetup"]
`
	p, err := ParseProject(src)
	if err != nil {
		t.Fatal(err)
	}
	if len(p.Scenarios) != 2 {
		t.Fatalf("parsed %d scenarios, want 2: %v", len(p.Scenarios), p.Scenarios)
	}
	if got := p.Scenarios["freeplay-plus"]; len(got) != 1 || got[0] != ScenarioControlEntry {
		t.Errorf("freeplay-plus chain is %v", got)
	}
	back, err := ParseProject(p.TOML())
	if err != nil {
		t.Fatalf("the rendered manifest does not parse: %v\n%s", err, p.TOML())
	}
	for name, chain := range p.Scenarios {
		got := back.Scenarios[name]
		if len(got) != len(chain) {
			t.Errorf("%s: round-tripped as %v, was %v", name, got, chain)
			continue
		}
		for i := range chain {
			if got[i] != chain[i] {
				t.Errorf("%s[%d]: %q, was %q", name, i, got[i], chain[i])
			}
		}
	}
}
