-- Round 2's measurement harness: what a typed argument block costs against the
-- tier-2 map, for the same GUI element spec.
--
-- THIS IS A MEASUREMENT HARNESS, NOT SHIPPING CODE, and it differs from round
-- 4b's in the way that matters: 4b measured PROTOTYPES of two encodings written
-- beside fk_abi.lua, because the feature did not exist. This measures the
-- SHIPPED path -- the real runtime/lua/fk_abi.lua, the real generated `sig` for
-- LuaGuiElement::add dumped out of the real generator, M.call against
-- M.call_typed -- so the only thing standing in for the game is the engine's own
-- `add`, which is a C++ GUI construction and cannot be had here at all.
--
-- THE ORACLE CAVEAT APPLIES AND POINTS ONE WAY. bin/lua52f reads a Lua table
-- 4-6x faster than Factorio does; both legs here are table-dominated, so the
-- ratio between them is the conservative half of the estimate. The absolute
-- nanoseconds are not a game figure and are not quoted as one.
--
-- Driven by bench.py, which supplies MEMLUA, MEMBERS, ABIDIR, LEG and REPS.

package.path = ABIDIR .. "/?.lua"
local H = require("fk_abi")

local Mod = MODTAB
local IO = Mod.memio
H.bind_memory(IO)
H.bind_read_string(Mod.read_string)
H.bind_globals({})

local allocNext = 262144
H.bind_alloc(function(n)
  local p = allocNext
  allocNext = allocNext + n
  if allocNext > 500000 then allocNext = 262144 end
  return p
end, function() end)
H.bind_scratch(400000, 100000)

-- THE REAL MEMBER TABLE, generated by the real generator. MEMBERS is the chunk
-- `fklua`'s own LuaSourceWith produced for member 1932 alone.
local api = MEMBERS
H.bind_members(api.members)
local MID = 1932
local sig = api.members[MID].sig

-- The stand-in engine object. Engine-shaped in the one way that matters here:
-- `add` reads the discriminating key, so neither decode can be optimised away
-- by a reader who assumed the table was never used.
local addCount = 0
local child = { valid = true, name = "child" }
local parent = { valid = true }
parent.add = function(spec)
  addCount = addCount + 1
  if spec.type == nil then error("add: no type") end
  if spec.name == nil then error("add: no name") end
  return child
end
local parentH = H.transient(parent)

local ARGP_DYN, ARGP_TYPED, RETP = 2048, 8192, 1024

-- ---------------------------------------------------------------------------
-- ONE SPEC, TWO ENCODINGS, WRITTEN ONCE OUTSIDE THE TIMED LOOP.
--
-- What is being timed is the DECODE, which is where 86% of a GUI element's cost
-- was measured to be (agents/drafts/r4b-batched-gui-add.md). The guest-side
-- encode is real work too and it is not in either leg, for the reason 4b's own
-- note gives: the guest half is hoisted in both forms and the host half is what
-- the wire shape decides.
--
-- The corpus is one row of an audited GUI application's table: a button with
-- type, name, caption, style and tooltip. Three of those are flat strings in the
-- typed block and two are LocalisedStrings, which are unions and therefore stay
-- tier-2 slots inside it -- so this is the honest mixed case rather than a block
-- of five (ptr, len) pairs.
-- ---------------------------------------------------------------------------
local specMixed = {
  type = "button",
  name = "row-7",
  caption = "Launch",
  style = "green_button",
  tooltip = "Sends the rocket",
}

-- ...AND THE SAME FIVE FIELDS WITH NOTHING UNION-TYPED IN THEM, which is the
-- other end of the honest range. `caption` and `tooltip` are LocalisedStrings --
-- a string OR an array -- so they are unions and stay tier-2 SLOTS inside the
-- block; `enabled` and `index` are a bool and a number and are flat. The two
-- corpora differ only in that, so the gap between their two ratios is what a
-- union-typed field costs the typed form.
local specFlat = {
  type = "button",
  name = "row-7",
  style = "green_button",
  enabled = true,
  index = 3,
}

local ARGP_DYN_F, ARGP_TYPED_F = 4096, 16384

H.write_dyn(ARGP_DYN, specMixed)
H.write_struct(sig.targs[1].fields, ARGP_TYPED + sig.targs[1].at, specMixed)
H.write_dyn(ARGP_DYN_F, specFlat)
H.write_struct(sig.targs[1].fields, ARGP_TYPED_F + sig.targs[1].at, specFlat)
-- The variant tail is ABSENT in both, which is the common case: everything
-- these corpora carry is a shared parameter. Its presence byte is already zero.
IO.st8(ARGP_TYPED + sig.targs[2].has, 0)
IO.st8(ARGP_TYPED_F + sig.targs[2].has, 0)

-- ---------------------------------------------------------------------------
-- The legs.
-- ---------------------------------------------------------------------------
local call, call_typed = H.call, H.call_typed
local read_dyn, read_struct = H.read_dyn, H.read_struct
local tfields = sig.targs[1].fields

local legs = {}

-- The floor: a plain Lua call taking and returning one value, measured twice
-- bracketing everything it qualifies.
local function nothing(x) return x end
legs.floor = function(n)
  local s = 0
  for _ = 1, n do s = s + nothing(1) end
  return s
end

-- WHAT A GUEST DOES TODAY: one tier-2 map through fk.call.
legs.call_dyn = function(n)
  for _ = 1, n do call(parentH, MID, ARGP_DYN, RETP) end
end

-- WHAT THIS ROUND SHIPS: the same spec as a tier-1 block through fk.call_typed.
legs.call_typed = function(n)
  for _ = 1, n do call_typed(parentH, MID, ARGP_TYPED, RETP) end
end

-- The two decodes with no dispatch and no engine call under them, which is what
-- says how much of the difference is the DECODE rather than the plumbing around
-- it. Same ablation 4b's table uses.
legs.decode_dyn = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_DYN) end
  return t
end

legs.decode_typed = function(n)
  local t
  for _ = 1, n do t = read_struct(tfields, ARGP_TYPED) end
  return t
end

-- THE SAME FOUR LEGS OVER THE ALL-FLAT CORPUS.
legs.call_dyn_flat = function(n)
  for _ = 1, n do call(parentH, MID, ARGP_DYN_F, RETP) end
end

legs.call_typed_flat = function(n)
  for _ = 1, n do call_typed(parentH, MID, ARGP_TYPED_F, RETP) end
end

legs.decode_dyn_flat = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_DYN_F) end
  return t
end

legs.decode_typed_flat = function(n)
  local t
  for _ = 1, n do t = read_struct(tfields, ARGP_TYPED_F) end
  return t
end

-- WHY THE ALL-FLAT CORPUS'S DYN LEG IS DEARER THAN THE MIXED ONE, which is the
-- one counter-intuitive row in the table and is worth an ablation rather than a
-- hypothesis. Two five-pair maps with the same five keys, differing only in
-- whether the VALUES are short strings or numbers.
--
-- A tier-2 number is a DOUBLE by construction -- Lua has one numeric type and
-- the tag says DYN_NUM -- so read_dyn reads it with ldf64, which in emitted Lua
-- is a two-word load plus a string.pack/string.unpack round trip. A six-byte
-- string takes read_string's n < 8 fast path. So the tier-2 form has no cheap
-- way to carry a small integer, and a typed block gives the same field its
-- declared width (a u32 is one ld32, a bool one ld8).
local ARGP_STRS, ARGP_NUMS = 20480, 24576
H.write_dyn(ARGP_STRS, { a = "button", b = "row-7", c = "green", d = "small", e = "large" })
H.write_dyn(ARGP_NUMS, { a = 1, b = 2, c = 3, d = 4, e = 5 })

legs.decode_dyn_strvals = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_STRS) end
  return t
end

legs.decode_dyn_numvals = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_NUMS) end
  return t
end

-- HAND-WRITTEN LUA building the same table, which is the thing a mod author
-- would have written instead of using this mod at all. Its own column.
legs.lua_add = function(n)
  for _ = 1, n do
    parent.add({
      type = "button",
      name = "row-7",
      caption = "Launch",
      style = "green_button",
      tooltip = "Sends the rocket",
    })
  end
end

-- ---------------------------------------------------------------------------
-- ROUND 4b'S RE-JUDGMENT: does BATCHING typed specs still buy anything?
--
-- 4b measured an array of tier-2 maps at 0.87x and concluded the survey's shape
-- was not a lever, and that the lever was NOT RE-MARSHALLING STRINGS -- 12x, on
-- top of a flat encoding it predicted at 3.3x. Round 2 then shipped the flat
-- encoding and measured it at 0.735x on this very corpus rather than 3.3x,
-- because two of `add`'s five audited fields are LocalisedStrings and a union
-- stays a tier-2 slot inside the block. So 4b's prediction is dead and its
-- REMAINING claim -- the per-batch string pool -- has to be re-measured against
-- what shipped rather than against what it assumed.
--
-- WHAT THE PROTOTYPE IS. `batch_typed` is `count` copies of THE SAME typed block
-- the shipped path uses, plus one per-batch string table, with every plain-string
-- field carrying a u32 INDEX into that table where the shipped block carries a
-- (ptr, len). Its decode walks `tfields` exactly as read_struct does, so the
-- field count, the presence bytes and the union slots are identical on both
-- sides and the ONLY differences are the two the design claims: one dispatch for
-- the batch instead of one per element, and each DISTINCT string decoded once.
--
-- THE UNION SLOTS CANNOT POOL, which is the whole reason this needed measuring.
-- `caption` and `tooltip` are LocalisedStrings, so they are K_DYN slots and go
-- through read_dyn per element in both forms. Of the audited row's five fields
-- only three are poolable, and of those three only `type` and `style` repeat --
-- `name` is distinct per element by construction, because a GUI element's name
-- is what a handler finds it by.
-- ---------------------------------------------------------------------------

local G = 50                       -- elements in one window, 4b's own corpus size
-- Addresses above the allocator's window (262144..500000) and the scratch
-- region (400000..500000), inside the harness's own 16 pages. 50 blocks of 248
-- is 12.4 KB apiece, so everything below fits with room to spare.
local BATCH_SPECS = 520000         -- count copies of the typed block
local BATCH_PERCALL = 560000       -- ...and the same specs for the per-call leg
local STRTAB = 600000              -- count, then (ptr,len) pairs
local STRBYTES = 610000            -- the bytes they point at
local TSIZE = api.members[MID].targsize

-- The corpus: G elements shaped like the rows of a table. `type` cycles over
-- three values and `style` is one, which is what a real window looks like;
-- `name` and `caption` are distinct per element, which is what stops the pool
-- from flattering itself.
local batchSpecs = {}
local kinds = { "flow", "label", "button" }
for i = 1, G do
  batchSpecs[i] = {
    type = kinds[(i - 1) % 3 + 1],
    name = "row-" .. i .. "-cell",
    caption = "Row " .. i,
    style = "green_button",
    tooltip = "Sends the rocket",
  }
end

-- The per-call side, written once outside every timed leg exactly as the single
-- specs above are: what is timed is the DECODE and the dispatch, not the encode.
for i = 1, G do
  local at = BATCH_PERCALL + (i - 1) * TSIZE
  H.write_struct(sig.targs[1].fields, at + sig.targs[1].at, batchSpecs[i])
  IO.st8(at + sig.targs[2].has, 0)
end

-- The BATCH side: the same blocks, with every plain-string field replaced by a
-- u32 index into the table below. Built here, once, for the same reason.
local pool, poolIndex = {}, {}
local function intern(str)
  local ix = poolIndex[str]
  if ix == nil then
    ix = #pool
    pool[#pool + 1] = str
    poolIndex[str] = ix
  end
  return ix
end
for i = 1, G do
  local at = BATCH_SPECS + (i - 1) * TSIZE
  H.write_struct(sig.targs[1].fields, at + sig.targs[1].at, batchSpecs[i])
  IO.st8(at + sig.targs[2].has, 0)
  for _, f in ipairs(tfields) do
    if f.kind == H.K_STR and (f.has == nil or IO.ld8(at + sig.targs[1].at + f.has) ~= 0) then
      local a = at + sig.targs[1].at + f.at
      local n = IO.ld32(a + 4)
      if n > 0 then
        IO.st32(a, intern(H.read_string(IO.ld32(a), n)))
        IO.st32(a + 4, 0)
      end
    end
  end
end
-- ...and the table itself: a count, then (ptr, len) pairs, then the bytes.
IO.st32(STRTAB, #pool)
local bytesAt = STRBYTES
for i = 1, #pool do
  IO.wstr(bytesAt, pool[i])
  IO.st32(STRTAB + 4 + (i - 1) * 8, bytesAt)
  IO.st32(STRTAB + 8 + (i - 1) * 8, #pool[i])
  bytesAt = bytesAt + #pool[i]
end

local read_string, read_value = H.read_string, H.read_value

-- The prototype M.batch_add's decode, in the style fk_abi.lua would have written
-- it: the string table once, then the spec walk per element.
local function batchAdd(specp, count, tabp)
  local n = IO.ld32(tabp)
  local strs = {}
  for i = 1, n do
    local e = tabp + 4 + (i - 1) * 8
    strs[i] = read_string(IO.ld32(e), IO.ld32(e + 4))
  end
  local made = 0
  for e = 0, count - 1 do
    local at = specp + e * TSIZE + sig.targs[1].at
    local tbl = {}
    for _, f in ipairs(tfields) do
      if f.has == nil or IO.ld8(at + f.has) ~= 0 then
        if f.kind == H.K_STR then
          tbl[f.name] = strs[IO.ld32(at + f.at) + 1]
        else
          tbl[f.name] = read_value(f, at)
        end
      end
    end
    parent.add(tbl)
    made = made + 1
  end
  return made
end

-- THE BASELINE FOR THIS COMPARISON IS THE SHIPPED TYPED CALL, not the tier-2
-- one. 4b's own baseline was the dyn form, and round 2 moved that floor.
legs.window_percall_typed = function(n)
  for _ = 1, n do
    for i = 1, G do
      call_typed(parentH, MID, BATCH_PERCALL + (i - 1) * TSIZE, RETP)
    end
  end
end

legs.window_batch_pooled = function(n)
  for _ = 1, n do batchAdd(BATCH_SPECS, G, STRTAB) end
end

-- ...and the same batch with every string decoded per ELEMENT rather than once
-- per batch, which is the pool ablated and nothing else. The difference between
-- this leg and the one above IS the pool.
local function batchAddNoPool(specp, count, tabp)
  local made = 0
  for e = 0, count - 1 do
    local at = specp + e * TSIZE + sig.targs[1].at
    local tbl = {}
    for _, f in ipairs(tfields) do
      if f.has == nil or IO.ld8(at + f.has) ~= 0 then
        if f.kind == H.K_STR then
          local ix = IO.ld32(at + f.at)
          local ent = tabp + 4 + ix * 8
          tbl[f.name] = read_string(IO.ld32(ent), IO.ld32(ent + 4))
        else
          tbl[f.name] = read_value(f, at)
        end
      end
    end
    parent.add(tbl)
    made = made + 1
  end
  return made
end

legs.window_batch_nopool = function(n)
  for _ = 1, n do batchAddNoPool(BATCH_SPECS, G, STRTAB) end
end

-- ---------------------------------------------------------------------------
-- ANTI-VACUITY: every leg really did its work, checked before anything is
-- timed. A decode that silently produced nothing would be the fastest leg here.
-- ---------------------------------------------------------------------------
if VERIFY then
  local out = {}
  local before = addCount
  if call(parentH, MID, ARGP_DYN, RETP) ~= H.OK then error("dyn call failed") end
  if call_typed(parentH, MID, ARGP_TYPED, RETP) ~= H.OK then error("typed call failed") end
  out[#out + 1] = "add calls: " .. (addCount - before)
  -- THE TWO DECODES AGREE, in both corpora, which is the correctness half
  -- stated in the same place as the timing half: a faster leg computing a
  -- different table is not a faster leg.
  for _, c in ipairs({ { "mixed", ARGP_DYN, ARGP_TYPED }, { "flat", ARGP_DYN_F, ARGP_TYPED_F } }) do
    local d, s = read_dyn(c[2]), read_struct(tfields, c[3])
    local kd, ks = 0, 0
    for _ in pairs(d) do kd = kd + 1 end
    for _ in pairs(s) do ks = ks + 1 end
    out[#out + 1] = c[1] .. " keys: dyn " .. kd .. ", typed " .. ks
    for k, v in pairs(d) do
      if s[k] ~= v then out[#out + 1] = "DISAGREE " .. c[1] .. " " .. tostring(k) end
    end
    for k, v in pairs(s) do
      if d[k] ~= v then out[#out + 1] = "DISAGREE " .. c[1] .. " " .. tostring(k) end
    end
  end
  out[#out + 1] = "targsize: " .. api.members[MID].targsize ..
    "  argsize: " .. api.members[MID].argsize
  -- THE WINDOW CORPUS: both forms build G elements, and the tables they build
  -- are compared key for key. A batch that decoded faster because it produced
  -- less is the vacuity this block exists to catch, and the pool is exactly the
  -- mechanism that could do it.
  local b4 = addCount
  local made = batchAdd(BATCH_SPECS, G, STRTAB)
  local batchAdds = addCount - b4
  b4 = addCount
  for i = 1, G do call_typed(parentH, MID, BATCH_PERCALL + (i - 1) * TSIZE, RETP) end
  out[#out + 1] = "window: batch made " .. made .. "/" .. batchAdds ..
    ", per-call made " .. (addCount - b4) .. " of " .. G
  out[#out + 1] = "pool: " .. #pool .. " distinct strings for " .. G ..
    " elements"
  local agree, first = true, nil
  for i = 1, G do
    local at = BATCH_SPECS + (i - 1) * TSIZE + sig.targs[1].at
    local bt = {}
    for _, f in ipairs(tfields) do
      if f.has == nil or IO.ld8(at + f.has) ~= 0 then
        if f.kind == H.K_STR then
          local n2 = IO.ld32(at + f.at)
          bt[f.name] = pool[n2 + 1]
        else
          bt[f.name] = read_value(f, at)
        end
      end
    end
    local pt = read_struct(tfields, BATCH_PERCALL + (i - 1) * TSIZE + sig.targs[1].at)
    for k, v in pairs(pt) do
      if bt[k] ~= v then agree = false first = first or (k .. "@" .. i) end
    end
    for k, v in pairs(bt) do
      if pt[k] ~= v then agree = false first = first or (k .. "@" .. i) end
    end
  end
  out[#out + 1] = "window encodings agree: " .. tostring(agree) ..
    (first and (" first " .. first) or "")
  print(table.concat(out, "\n"))
  return
end

local f = legs[LEG]
if f == nil then error("no such leg: " .. tostring(LEG)) end
f(REPS)
print("done")
