-- Round 2's measurement harness: what a typed argument block costs against the
-- tier-2 map, for the same GUI element spec.
--
-- THIS IS A MEASUREMENT HARNESS, NOT SHIPPING CODE, and it differs from round
-- 4b's in the way that matters: 4b measured PROTOTYPES of two encodings written
-- beside fk_abi.lua, because the feature did not exist. This measures the
-- SHIPPED path -- the real runtime/lua/fk_abi.lua, the real generated `sig` for
-- LuaGuiElement::add dumped out of the real generator, M.call against
-- M.call_typed -- so the only thing standing in for the game is the engine's own
-- `add`, which is a C++ GUI construction and cannot be had here at all.
--
-- THE ORACLE CAVEAT APPLIES AND POINTS ONE WAY. bin/lua52f reads a Lua table
-- 4-6x faster than Factorio does; both legs here are table-dominated, so the
-- ratio between them is the conservative half of the estimate. The absolute
-- nanoseconds are not a game figure and are not quoted as one.
--
-- Driven by bench.py, which supplies MEMLUA, MEMBERS, ABIDIR, LEG and REPS.

package.path = ABIDIR .. "/?.lua"
local H = require("fk_abi")

local Mod = MODTAB
local IO = Mod.memio
H.bind_memory(IO)
H.bind_read_string(Mod.read_string)
H.bind_globals({})

local allocNext = 262144
H.bind_alloc(function(n)
  local p = allocNext
  allocNext = allocNext + n
  if allocNext > 500000 then allocNext = 262144 end
  return p
end, function() end)
H.bind_scratch(400000, 100000)

-- THE REAL MEMBER TABLE, generated by the real generator. MEMBERS is the chunk
-- `fklua`'s own LuaSourceWith produced for member 1932 alone.
local api = MEMBERS
H.bind_members(api.members)
local MID = 1932
local sig = api.members[MID].sig

-- The stand-in engine object. Engine-shaped in the one way that matters here:
-- `add` reads the discriminating key, so neither decode can be optimised away
-- by a reader who assumed the table was never used.
local addCount = 0
local child = { valid = true, name = "child" }
local parent = { valid = true }
parent.add = function(spec)
  addCount = addCount + 1
  if spec.type == nil then error("add: no type") end
  if spec.name == nil then error("add: no name") end
  return child
end
local parentH = H.transient(parent)

local ARGP_DYN, ARGP_TYPED, RETP = 2048, 8192, 1024

-- ---------------------------------------------------------------------------
-- ONE SPEC, TWO ENCODINGS, WRITTEN ONCE OUTSIDE THE TIMED LOOP.
--
-- What is being timed is the DECODE, which is where 86% of a GUI element's cost
-- was measured to be (agents/drafts/r4b-batched-gui-add.md). The guest-side
-- encode is real work too and it is not in either leg, for the reason 4b's own
-- note gives: the guest half is hoisted in both forms and the host half is what
-- the wire shape decides.
--
-- The corpus is one row of an audited GUI application's table: a button with
-- type, name, caption, style and tooltip. Three of those are flat strings in the
-- typed block and two are LocalisedStrings, which are unions and therefore stay
-- tier-2 slots inside it -- so this is the honest mixed case rather than a block
-- of five (ptr, len) pairs.
-- ---------------------------------------------------------------------------
local specMixed = {
  type = "button",
  name = "row-7",
  caption = "Launch",
  style = "green_button",
  tooltip = "Sends the rocket",
}

-- ...AND THE SAME FIVE FIELDS WITH NOTHING UNION-TYPED IN THEM, which is the
-- other end of the honest range. `caption` and `tooltip` are LocalisedStrings --
-- a string OR an array -- so they are unions and stay tier-2 SLOTS inside the
-- block; `enabled` and `index` are a bool and a number and are flat. The two
-- corpora differ only in that, so the gap between their two ratios is what a
-- union-typed field costs the typed form.
local specFlat = {
  type = "button",
  name = "row-7",
  style = "green_button",
  enabled = true,
  index = 3,
}

local ARGP_DYN_F, ARGP_TYPED_F = 4096, 16384

H.write_dyn(ARGP_DYN, specMixed)
H.write_struct(sig.targs[1].fields, ARGP_TYPED + sig.targs[1].at, specMixed)
H.write_dyn(ARGP_DYN_F, specFlat)
H.write_struct(sig.targs[1].fields, ARGP_TYPED_F + sig.targs[1].at, specFlat)
-- The variant tail is ABSENT in both, which is the common case: everything
-- these corpora carry is a shared parameter. Its presence byte is already zero.
IO.st8(ARGP_TYPED + sig.targs[2].has, 0)
IO.st8(ARGP_TYPED_F + sig.targs[2].has, 0)

-- ---------------------------------------------------------------------------
-- The legs.
-- ---------------------------------------------------------------------------
local call, call_typed = H.call, H.call_typed
local read_dyn, read_struct = H.read_dyn, H.read_struct
local tfields = sig.targs[1].fields

local legs = {}

-- The floor: a plain Lua call taking and returning one value, measured twice
-- bracketing everything it qualifies.
local function nothing(x) return x end
legs.floor = function(n)
  local s = 0
  for _ = 1, n do s = s + nothing(1) end
  return s
end

-- WHAT A GUEST DOES TODAY: one tier-2 map through fk.call.
legs.call_dyn = function(n)
  for _ = 1, n do call(parentH, MID, ARGP_DYN, RETP) end
end

-- WHAT THIS ROUND SHIPS: the same spec as a tier-1 block through fk.call_typed.
legs.call_typed = function(n)
  for _ = 1, n do call_typed(parentH, MID, ARGP_TYPED, RETP) end
end

-- The two decodes with no dispatch and no engine call under them, which is what
-- says how much of the difference is the DECODE rather than the plumbing around
-- it. Same ablation 4b's table uses.
legs.decode_dyn = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_DYN) end
  return t
end

legs.decode_typed = function(n)
  local t
  for _ = 1, n do t = read_struct(tfields, ARGP_TYPED) end
  return t
end

-- THE SAME FOUR LEGS OVER THE ALL-FLAT CORPUS.
legs.call_dyn_flat = function(n)
  for _ = 1, n do call(parentH, MID, ARGP_DYN_F, RETP) end
end

legs.call_typed_flat = function(n)
  for _ = 1, n do call_typed(parentH, MID, ARGP_TYPED_F, RETP) end
end

legs.decode_dyn_flat = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_DYN_F) end
  return t
end

legs.decode_typed_flat = function(n)
  local t
  for _ = 1, n do t = read_struct(tfields, ARGP_TYPED_F) end
  return t
end

-- WHY THE ALL-FLAT CORPUS'S DYN LEG IS DEARER THAN THE MIXED ONE, which is the
-- one counter-intuitive row in the table and is worth an ablation rather than a
-- hypothesis. Two five-pair maps with the same five keys, differing only in
-- whether the VALUES are short strings or numbers.
--
-- A tier-2 number is a DOUBLE by construction -- Lua has one numeric type and
-- the tag says DYN_NUM -- so read_dyn reads it with ldf64, which in emitted Lua
-- is a two-word load plus a string.pack/string.unpack round trip. A six-byte
-- string takes read_string's n < 8 fast path. So the tier-2 form has no cheap
-- way to carry a small integer, and a typed block gives the same field its
-- declared width (a u32 is one ld32, a bool one ld8).
local ARGP_STRS, ARGP_NUMS = 20480, 24576
H.write_dyn(ARGP_STRS, { a = "button", b = "row-7", c = "green", d = "small", e = "large" })
H.write_dyn(ARGP_NUMS, { a = 1, b = 2, c = 3, d = 4, e = 5 })

legs.decode_dyn_strvals = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_STRS) end
  return t
end

legs.decode_dyn_numvals = function(n)
  local t
  for _ = 1, n do t = read_dyn(ARGP_NUMS) end
  return t
end

-- HAND-WRITTEN LUA building the same table, which is the thing a mod author
-- would have written instead of using this mod at all. Its own column.
legs.lua_add = function(n)
  for _ = 1, n do
    parent.add({
      type = "button",
      name = "row-7",
      caption = "Launch",
      style = "green_button",
      tooltip = "Sends the rocket",
    })
  end
end

-- ---------------------------------------------------------------------------
-- ANTI-VACUITY: every leg really did its work, checked before anything is
-- timed. A decode that silently produced nothing would be the fastest leg here.
-- ---------------------------------------------------------------------------
if VERIFY then
  local out = {}
  local before = addCount
  if call(parentH, MID, ARGP_DYN, RETP) ~= H.OK then error("dyn call failed") end
  if call_typed(parentH, MID, ARGP_TYPED, RETP) ~= H.OK then error("typed call failed") end
  out[#out + 1] = "add calls: " .. (addCount - before)
  -- THE TWO DECODES AGREE, in both corpora, which is the correctness half
  -- stated in the same place as the timing half: a faster leg computing a
  -- different table is not a faster leg.
  for _, c in ipairs({ { "mixed", ARGP_DYN, ARGP_TYPED }, { "flat", ARGP_DYN_F, ARGP_TYPED_F } }) do
    local d, s = read_dyn(c[2]), read_struct(tfields, c[3])
    local kd, ks = 0, 0
    for _ in pairs(d) do kd = kd + 1 end
    for _ in pairs(s) do ks = ks + 1 end
    out[#out + 1] = c[1] .. " keys: dyn " .. kd .. ", typed " .. ks
    for k, v in pairs(d) do
      if s[k] ~= v then out[#out + 1] = "DISAGREE " .. c[1] .. " " .. tostring(k) end
    end
    for k, v in pairs(s) do
      if d[k] ~= v then out[#out + 1] = "DISAGREE " .. c[1] .. " " .. tostring(k) end
    end
  end
  out[#out + 1] = "targsize: " .. api.members[MID].targsize ..
    "  argsize: " .. api.members[MID].argsize
  print(table.concat(out, "\n"))
  return
end

local f = legs[LEG]
if f == nil then error("no such leg: " .. tostring(LEG)) end
f(REPS)
print("done")
