//! Generated Factorio API bindings for Rust.
//!
//! `api.rs` is generated by `fklua gen-bindings` and committed, so a build
//! needs neither the game nor the network. Do not edit it: `--check` fails if
//! it drifts from `api/<version>/runtime-api.json`.
#![no_std]

extern crate alloc;

mod api;
pub use api::*;
