#!/usr/bin/env python3
"""Generate internal/wasm/kindnames_gen.go from watgo's InstrKind constants.

wasmir.InstrKind has no String method, so without this every unsupported
instruction would report as an opaque number. The whole reason we own an adapter
rather than using watgo directly is to say "function 'foo' uses f64.sqrt, not
supported until M3" instead of "invalid module", and that needs real names.

Run: python3 scripts/gen-kindnames.py   (after bumping watgo)
"""
import pathlib
import re
import subprocess
import sys

# Prefixes that are followed by '.' in wasm text format rather than '_'.
TYPE_PREFIXES = [
    "i8x16", "i16x8", "i32x4", "i64x2", "f32x4", "f64x2", "v128",
    "i32", "i64", "f32", "f64",
    "local", "global", "memory", "table", "elem", "data",
    "struct", "array", "extern", "any", "func", "i31", "ref",
]


def split_camel(s):
    """ExtractLane -> [Extract, Lane]; Load8U -> [Load8, U]; TruncSatF32S -> [Trunc, Sat, F32, S]."""
    return re.findall(r"[A-Z][a-z]*\d*|\d+", s)


def opcode_name(const):
    body = const[len("Instr"):]
    lowered = body.lower()
    for p in TYPE_PREFIXES:
        if lowered.startswith(p):
            # Guard against 'Function' matching the 'func' prefix, and similar:
            # the character after the prefix must start a new word.
            rest = body[len(p):]
            if rest and not rest[0].isupper() and not rest[0].isdigit():
                continue
            if not rest:
                return p
            return f"{p}.{'_'.join(w.lower() for w in split_camel(rest))}"
    return "_".join(w.lower() for w in split_camel(body))


def main():
    modcache = subprocess.run(
        ["go", "env", "GOMODCACHE"], capture_output=True, text=True, check=True
    ).stdout.strip()
    version = None
    for line in pathlib.Path("go.mod").read_text().splitlines():
        m = re.search(r"github\.com/eliben/watgo (v\S+)", line)
        if m:
            version = m.group(1)
    if not version:
        sys.exit("watgo not found in go.mod")

    src_dir = pathlib.Path(modcache) / "github.com" / "eliben" / f"watgo@{version}" / "wasmir"
    if not src_dir.is_dir():
        sys.exit(f"not found: {src_dir} (run `go mod download`)")

    consts = []
    for path in sorted(src_dir.glob("*.go")):
        text = path.read_text()
        # Only pick up identifiers inside a const block that are InstrKind
        # members; the declaration style is `\tInstrFoo` one per line.
        for m in re.finditer(r"^\t(Instr[A-Za-z0-9]+)", text, re.M):
            consts.append(m.group(1))
    consts = sorted(set(consts))
    if not consts:
        sys.exit("no InstrKind constants found")

    out = [
        "// Code generated by scripts/gen-kindnames.py. DO NOT EDIT.",
        "",
        "package wasm",
        "",
        'import "github.com/eliben/watgo/wasmir"',
        "",
        "// kindNames maps every watgo instruction kind to its WebAssembly text-format",
        "// opcode name, so that an unsupported instruction can be named in a",
        "// diagnostic rather than reported as an opaque number.",
        f"// Generated from watgo {version}: {len(consts)} kinds.",
        "var kindNames = map[wasmir.InstrKind]string{",
    ]
    for c in consts:
        out.append(f'\twasmir.{c}: "{opcode_name(c)}",')
    out.append("}")
    out.append("")

    dest = pathlib.Path("internal/wasm/kindnames_gen.go")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out))
    print(f"wrote {dest} ({len(consts)} kinds from watgo {version})")

    for probe in ("InstrI32Add", "InstrLocalGet", "InstrBrIf", "InstrI32Load8U",
                  "InstrI32TruncSatF32S", "InstrI32x4ExtractLane", "InstrCallIndirect",
                  "InstrMemoryGrow", "InstrI32Extend8S", "InstrI32WrapI64"):
        if probe in consts:
            print(f"  {probe:28s} -> {opcode_name(probe)}")


if __name__ == "__main__":
    main()
